### ISSUE TITLE
Need some help with mochad 

### ISSUE THREAD

**Issue by sensboston** [njh/sonoff-ota-flash-cli#1]
Hi Nicholas, sorry for contacting you this way but I can't find any of your working contacts. 

I need to add one more function to mochad: ability to toggle unit off then on with fixed or configurable delay. I'm running mochad on RPi with X10 to toggle my lights in house but really want to be able to restart cable modem and router remotely. So, I need (on server side) to turn specific unit off, wait for nn second, than turn it on. Number of seconds can be hardcoded or whatever 😊

**Comment by sensboston** [comment]
Resolved by myself; no help from "open source community" was received (no one even replied yet). BTW, it's OK ;) 

P.S. But probably I'll never share my fixes...

**Comment by njh** [comment]
I sent this reply via email but Github doesn't seem to have added it to the issue. Not sure why.

> Sorry, I don't remember what mochad is!
> 
> I stopped using X10 quite a number of years ago and switched to LightWave RF.
> But now I am going look into using Sonoff modules instead (uses Wifi).

I am glad you managed to resolve your problem yourself.
