### ISSUE TITLE
Enhance for Sonoff Mini Extreme

### ISSUE THREAD

**Issue by schrej-zz** [njh/sonoff-ota-flash-cli#12]
Hi,
do you think, the script can be enhanced to also flash the new Sonoff Mini Extreme (ESP32), that also runs with Ewelink SW?

**Comment by njh** [comment]
I don't think so. 

The updated list of devices on [this page](https://sonoff.tech/diy-developer/) are:
- [BASICR3](http://sonoff.tech/product/wifi-diy-smart-switches/basicr3)
- [RFR3](http://sonoff.tech/product/wifi-smart-wall-swithes/rfr3)
- [MINIR2](http://sonoff.tech/product/wifi-diy-smart-switches/sonoff-mini)
- [MINIR3](http://sonoff.tech/product/diy-smart-switch/minir3/)
- [D1](http://sonoff.tech/product/wifi-diy-smart-switches/d1-smart-dimmer-switch)
- [SPM-Main](http://sonoff.tech/product/spm-main-spm-4relay/)
- [B02-BL-A60](https://itead.cc/product/sonoff-b02-bl-b05-bl-wi-fi-smart-led-bulb/)
- [B05-BL-A19](https://itead.cc/product/sonoff-b02-bl-b05-bl-wi-fi-smart-led-bulb/)
- [B05-BL-A60](https://itead.cc/product/sonoff-b02-bl-b05-bl-wi-fi-smart-led-bulb/)


There doesn't seem to be any mention of DIY Mode on the Sonoff Mini Extreme product page:
https://sonoff.tech/product/diy-smart-switches/minir4/

So I think you will have to use Serial to flash it.
