### ISSUE TITLE
Will script flash tasmota to mini r3 with s-mate for no neutral solution

### ISSUE THREAD

**Issue by LeighAS** [njh/sonoff-ota-flash-cli#13]
I used your script to flash my mini r2 and it worked great. I then realised that I have no neutral behind some of my switches in the back boxes (old house wiring). I have seen that this can be overcome using diodes and fusible resistors as shown here https://www.youtube.com/watch?v=oBR5O391m_c
however sonoff has an out of the box no neutral "mini r3 + s-mate" solution that feels less error prone and tidier. The question would your script successfully tasmotise this ota and if it can has tasmota been updated to have a configuration for this model. (some of this is clearly googleable and I apologise for my laziness in asking some of this here).

I am tempted to buy the mini r3 and s-mate and just try it working on a bench. Great work btw and thanks for sharing it.

**Comment by njh** [comment]
Sorry, I don't think this relates to OTA flashing of Sonoff devices.

I don't know how S-Mate works, but I think it would require support in Tasmota:
