### ISSUE TITLE
Installs Tasmota-lite, so Domoticz support missing

### ISSUE THREAD

**Issue by mjf2708** [njh/sonoff-ota-flash-cli#14]
Worked very well for me - Mac OS 13.0 - on MiniR2, but installs an 'old' Tasmota-lite version (9.5.0), without Domoticz support.
Once configured, I did OTA upgrade to latest Tasmota version (12.4.0).
Suggest change to script, please.

**Comment by njh** [comment]
The last parameter of the script is a URL, so you can install whatever you want:

```
./sonoff-ota-flash.sh [options] [<filename or url>]
```

Note that the Sonoff OTA updates are limited to downloading and installing a 520192 byte fireware file - and the latest version of Tasmota is 647216.

So to install a larger (non-lite) firmware, you must first install tastmota-lite and then upgrade to the full binary.
