### ISSUE TITLE
Locked on "Unlocking for OTA flashing"

### ISSUE THREAD

**Issue by kepe94** [njh/sonoff-ota-flash-cli#15]
Hi, 
after i run the script, terminal is locked on "Unlocking for OTA flashing..." for some time, and next receive this error 

curl: (52) Empty reply from server
Error posting to: http://xxxxxxxxxxx/zeroconf/ota_unlock

Help me, please?

**Comment by njh** [comment]
What device are you attempting to unlock?

Is it connected to the Internet, or just your computer?
Sonoff devices need to be able to "phone home" over the Internet to get permission to unlock.

**Comment by kepe94** [comment]
sonoff mini R2 3.7.3. Finally i unlock the sonoff and add on my homekit home, but not working..

**Comment by njh** [comment]
Glad you managed to flash it.

I personally use [Tasmota](https://github.com/arendst/tasmota) → [Mosquitto](https://mosquitto.org) → [homebridge-mqttthing](https://www.npmjs.com/package/homebridge-mqttthing) to control my lights using HomeKit.
