### ISSUE TITLE
Worked like a charm

### ISSUE THREAD

**Issue by Vartkat** [njh/sonoff-ota-flash-cli#3]
Work where other failed on a MiniR2 (with no jumper).

Would it work on a Sonoff TH ?

**Comment by njh** [comment]
Great to heat you got it working :)

Unfortunately I don't think it would work on a Sonoff TH, no.

The Sonoff website says that the following devices are support [DIY Mode](http://developers.sonoff.tech/sonoff-diy-mode-api-protocol.html):
* [Basic R3](https://sonoff.tech/product/wifi-diy-smart-switches/basicr3)
* [RFR3](https://sonoff.tech/product/wifi-smart-wall-swithes/rfr3)
* [Mini](https://sonoff.tech/product/wifi-diy-smart-switches/sonoff-mini)
* [D1 Dimmer](https://sonoff.tech/product/wifi-diy-smart-switches/d1-smart-dimmer-switch)

I tried doing it on a Sonoff S26 and it didn't work - I am not sure why some of their devices support DIY Mode and others don't...
