### ISSUE TITLE
Bricking MiniR2

### ISSUE THREAD

**Issue by jfrancais** [njh/sonoff-ota-flash-cli#4]
I've now bricked 2 devices trying to flash with this.  I run ./sonoff-ota-flash.sh and it detects my Sonoff, gets to the step of "Please wait for your device to finish flashing." and after restarting, it never comes back.  I get no wifi network.  The on off switch will still toggle the relay but I can't connect to it at all.  The s1 / s2 connected switch doesn't toggle the relay either.  I see a slow blink on the sonoff.  can you advise?

**Comment by jfrancais** [comment]
rapid power cycle of 10 power on offs brought it back to life.

**Comment by njh** [comment]
Glad you were able to bring the devices back to life.

Did you have any success with flashing it with Tasmota?

One of the issues I have found is that the device needs an Internet connection in order to perform the OTA unlocking.

**Comment by inamesh** [comment]
Hi, just to let you know that I had the exact same issue. After power cycling 10 times, I finally saw the "tasmota-xxxx" WiFi AP and was able to fully configure the device. Thank you for the script!

**Comment by jfrancais** [comment]
> Glad you were able to bring the devices back to life.
> 
> Did you have any success with flashing it with Tasmota?
> 
> One of the issues I have found is that the device needs an Internet connection in order to perform the OTA unlocking.

Yes, the flashing seemed to work, just when the flashing was complete it didn't seem to bring up the wifi.  The 10 time power cycle seemed to reset it and get the wifi AP showing (Tasmota-xxxx)

**Comment by dygeenen** [comment]
Hello,
I have the same problem with my sonoff, flash seems OK but no AP tasmota appearing
like OP said, the on off switch will still toggle, but the s1 / s2 connected switch doesn't toggle the relay and I can see a slow blink on the sonoff
after having power cycle several hundred times over 3 hours, it finally appeared (tasmota-6XXXX2-3XX4)
the second one I can't get anything, do you have a specific trick with your 10 power cycle?
any help is welcome

**Comment by dygeenen** [comment]
For information,
the first sonoff, I flashed it manually with Postman with the latest version from the website http://sonoff-ota.aelius.com/ 
the second sonoff was flashed with the script, which also seems to use the latest version by default
the 2 have the same bug of the AP tasmota which does not appear directly

my third sonoff, I just flashed it manually with Postman with version 9.1.0-lite of the same website, and the AP tasmota appeared directly at reboot

would there be a problem with the last build ?

_at this moment, my second sonoff is still not back to life :( so, any idea for this one stay welcome_

**Comment by OnekO** [comment]
@njh Should be possible to have the configuration of the builded binaries? Looks like there is a problem with the last version...

**Comment by OnekO** [comment]
I have solved the issue after the 10 power cycles, weird because them shoul be 7.
