### ISSUE TITLE
flash failed ???

### ISSUE THREAD

**Issue by Tigger86** [njh/sonoff-ota-flash-cli#5]
have done everything as described here..and everything looked great...then the sonoff mini r2 always just blinked regularly but gives no ssid (ap) ..what am I doing wrong ?

**Comment by Digl** [comment]
same here

**Comment by amamdani15** [comment]
Happened to me as well. i powercycled the sonoff 4-5 times quickly so it was only on for one second at a time. then it popped up like it should have. no idea why.

**Comment by amamdani15** [comment]
okay, looks like the magic number is 7 as mentioned here https://tasmota.github.io/docs/Device-Recovery/

I just flashed 4 of these devices and had to do it to each and every one. I wonder if it has to do with Tasmota 10.0.0, newest version might have some kinks to work out.

**Comment by amamdani15** [comment]
Also, i would recommend throwing it on a power strip and just flipping the switch, doing multiple at a time if possible. good luck!

**Comment by mikesimons** [comment]
Same here; the wifi access point just didn't show up without the power cycling on all four Mini R2s.
I don't see how it would be a fault with the script though. Most likely something to do with the Mini R2 and Tasmota.

Maybe worth a message in the script to say if the wifi point doesn't show up to do the power cycling?

**Comment by gonzzovela** [comment]
Have the same issue with two MiniR2.

When you mean a power cycle, is it to push the button for 40sec? Because even doing that, it does not show up it's wifi AP

**Comment by gonzzovela** [comment]
I answer myself.

Doing the 7 power cycle (powere on/off 7 times) worked and I have my devices on Tasmota working fine.

Thanks for the hint!

**Comment by njh** [comment]
Hm, all this doesn't sound good!

I have downgraded `tasmota-latest-lite.bin` to version 9.5.0.

If people want to upgrade to version 10, then it can always be done via Tasmota OTA upgrade.

**Comment by Tigger86** [comment]
I have now turned the plug on and off 7 times with a switch. But what am I doing wrong, please? I only see that the blue LED is either on or flashing. But an ap does not appear.

How can I make a downgrade?
Thanks for help

**Comment by njh** [comment]
@Tigger86 sorry for not responding. I'm afraid I don't have any experience of getting out of that situation. I hope you managed to resolve the issue.

Given that downgrading the `latest` version to `9.5.0` seems to have resolved the problem, I am going to close this issue. I guess someones needs to test to see if it is fixed in newer releases of Tasmota.
