### ISSUE TITLE
 Empty reply from server

### ISSUE THREAD

**Issue by steinmetz** [njh/sonoff-ota-flash-cli#6]
Hi, I am getting this error. Do you have any idea what I should do to fix it?

Thanks.

```
./sonoff-ota-flash.sh tasmota-latest-lite.bin
Checking new firmware file exists
OK

Looking up sha256sum for firmware
OK

Searching for Sonoff module on network...
Found module on network.
Hostname: eWeLink_10011f2dfb
IPv4 Address: 192.168.0.121

Getting Module Info...
curl: (52) Empty reply from server
Error posting to: http://192.168.0.121:8081/zeroconf/info

**Comment by njh** [comment]
Sorry for not responding. Did you work out what was wrong?

I have generally got _"Empty reply from server"_ when something has gone wrong but the modules unfortunately don't have specific error message to return.
