### ISSUE TITLE
manually call /zeroconf/ota_unlock

### ISSUE THREAD

**Issue by jonascoenen005** [njh/sonoff-ota-flash-cli#7]
Hello,

If i run the script, i'm getting the following error: Failed to create client object: Daemon not running

I'm running the Ubuntu app on windows installation. 

Could you help me to see why this is happening? Thanks!

**Comment by jonascoenen005** [comment]
Passing -i with the ip address seems to fix this issue!

**Comment by jonascoenen005** [comment]
I had to manually call the http://ipaddress:8081/zeroconf/ota_unlock to unlock OTA, after that the script succeeded

**Comment by njh** [comment]
Sorry, I have never tried the script on Windows.
To find the IP address automatically it needs the Avahai (Multicast DNS) daemon to be running (Linux).
Or on Mac it uses the Mac OS Multicast DNS resolver.

Slightly odd that you had to run the OTA Unlock Manually but glad you got it working in the end.
