### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by hesmith1029** [njh/sonoff-ota-flash-cli#8]
Not at all clear what operating systems this does or does NOT work on.

**Comment by njh** [comment]
I can add a section to the README on the Operating Systems that it has been tested on.
And encourage people to submit Pull Requests for their own experiences.

Did you find one that it does NOT work on?

**Comment by hesmith1029** [comment]
Having no luck with Windows 10

**Comment by njh** [comment]
I have added a section to the README about which OS versions the script has been tested with.
