### ISSUE TITLE
File server down

### ISSUE THREAD

**Issue by jellebosscher** [njh/sonoff-ota-flash-cli#9]
The hosted binaries of tasmota firmwares with SHA is down: http://sonoff-ota.aelius.com/

Script still works if binary is hosted locally.

**Comment by safemachine-1** [comment]
File server is down . So how can you upload the bin if you download it from http://ota.tasmota.com/tasmota/release-9.5.0/tasmota-lite.bin
?

**Comment by francoismassart** [comment]
👋 Hi there,
I did contact https://sonoff.tech/support/ in order to warn them that http://sonoff-ota.aelius.com/ was down...

UPDATE: I realized https://www.aelius.com/ is owned by @njh, not by sonoff

**Comment by jellebosscher** [comment]
@safeRetail I started up an apache file server on my local network and got the SHA for the binary I downloaded. Redirected the script to my local ip. 

@francoismassart Thanks!

**Comment by francoismassart** [comment]
@jellebosscher did you do it on a sonoff mini r2 ?
I just bricked 2 sonoff mini r2 but I don't know what's wrong, here is the log:


https://ota.tasmota.com/tasmota/release/tasmota-lite.bin
a421f9080117861b2c0dd30228779466d127269acfab34de0e2cf4fa1ed0e61b

```
Checking new firmware file exists
OK

Searching for Sonoff module on network...
Found module on network.
Hostname: eWeLink_100152efbd
IPv4 Address: 192.168.1.195

Getting Module Info...
 {
    "seq":3,
    "error":0,
    "data":
    {
        "switch":"off",
        "startup":"off",
        "pulse":"off",
        "pulseWidth":500,
        "ssid":"homenetwork",
        "otaUnlock":false,
        "fwVersion":"3.6.0",
        "deviceid":"100152efbd",
        "bssid":"cc:32:e5:b0:f2:f3",
        "signalStrength":-63
    }
 }

Unlocking for OTA flashing...
 {
    "seq":3,
    "error":0
 }

Proceed with flashing? [N/y] y
Requesting OTA flashing...
 {
    "seq":4,
    "error":0
 }

Please wait for your device to finish flashing.
```

It's been running for a while but, the tasmota network does not show up 👎

**Comment by njh** [comment]
Sorry the server is currently down. It has stopped booting and I have been unwell 🤒 

It could really do with some more reliable hosting but the other personal hosting I have, requires you to own the target hostname (`dl.itead.cn`), which I don't. Which is also a problem with commercial CDNs, such as CloudFlare.

Hopefully it will be up and running again soon...

**Comment by francoismassart** [comment]
My 2 Mini R2 are not bricked, after a restart I'm still able to use the "native" API https://sonoff.tech/sonoff-diy-developer-documentation-basicr3-rfr3-mini-http-api/ but it seems I cannot install the tasmota firmware...

**Comment by Too51oll** [comment]
Same here doesn't seam to work. I've self hosted the files, everything seam to work correctly but device does not flash with either tasmota nor esphome bin files. The Mini R2 becomes unresponsive until rebooted which brings it to previous original state.
![Screenshot 2022-04-13 143211](https://user-images.githubusercontent.com/60147239/163192624-a15ea67b-509c-4e30-9bb1-27788b56bca2.jpg)

**Comment by njh** [comment]
I run the server on mirrored dual SSDs using RAID-1. One of the SSDs has failed.

But the BIOS was still trying to boot using the failed drive.
It is back up and running now and a replacement SSD has been ordered.

I am closing this and have opened #10 instead, to address the reliability issues.

**Comment by njh** [comment]
I have just upgraded to more reliable hosting. Hopefully the server should be far less likely to go down now.

It is only costing me $3 per month, but any small donations to help with the running costs, would be appreciated:
[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/donate/?hosted_button_id=36V8QLH5X96DC)
